services:
  - type: web
    name: shopremi-web
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://remi_db_user:HiAmYVWiCYeRSlFIFHAhvLkdVGQ1GBDc@dpg-d0s2t83e5dus73a2nt20-a/remi_db
